### ISSUE TITLE
[BUG] - Correção na navegação do header

### ISSUE THREAD

**Issue by AndersonCRocha** [ifba-vca/bsi-ifba-web#24]
Ao clicar em Matriz Curricular, A página com a matriz é exibida corretamente, porém ao realizar o reload da página ocorre um erro 404 conforme print a seguir.

![image](https://user-images.githubusercontent.com/59173445/125805110-4f087dbc-1a2a-49c9-af6d-0750b6deb327.png)

**Comment by filipecancio** [comment]
Para fazer as rotas do site eu usei o `react-router-dom` e para deploy, botei o firebase hosting, ao que parece é necessário fazer alguma configuração no `firebase.json` pra traçar essas rotas, ou algo assim.

**Comment by filipecancio** [comment]
algo tipo isso:
```
"hosting": {
  // Add the "rewrites" section within "hosting"
  "rewrites": [ {
    "source": "**",
    "destination": "/index.html"
  } ]
}
``` 
de acordo com essa [documentação](https://firebase.google.com/docs/hosting/full-config?hl=pt-br).
